version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: ideaboard-db
    environment:
      POSTGRES_DB: ideaboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (Node.js + Express + GraphQL)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ideaboard-backend
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ideaboard
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ideaboard-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
